### PR TITLE
Re-baseline DPP to v0.4.0

### LINKED ISSUE #38: Product Passport Data Model
@onthebreeze has hinted at an update to the [Product Passport data model](https://uncefact.github.io/spec-untp/docs/specification/DigitalProductPassport), drawing on insights from [CIRPASS](https://cirpassproject.eu/about-cirpass/).

This ticket is meant to prompt a review and discussion of the suggested changes.

### PR DESCRIPTION
**Pull request by onthebreeze**
Closes #38

### CODE REVIEW

**Review by nissimsan — APPROVED** [review]

**Comment by nissimsan** [comment]
@onthebreeze, I fixed some file formatting.

The schema for context is abstract and hints towards some wrong assumptions arounds what we can and should expect from spec users/implementers. I'm not blocking merge, but we need to this replaced with an actual context file IMO. There is probably a discussion to be had around tooling in that regard.

**Comment by ashleythedeveloper** [comment]
@nissimsan , I agree. I have been collaborating with @kshychko and @Fak3 on this. While it still requires more work, we have made a start [here](https://test.uncefact.org/vocabulary/untp/home).

I would be happy to continue working with @kshychko, @Fak3, and under your guidance to resolve this issue.

**Comment by kshychko** [comment]
@nissimsan, @ashleythedeveloper I'll get the "better" JSON-LD context file created for DPP in a couple of days.

**Comment by nissimsan** [comment]
@ashleythedeveloper , @kshychko , great that there is something brewing already. 

Noting that https://test.uncefact.org/vocabulary/untp/dpp/ProductPassport.jsonld is equally abstract (not a context, but a json schema for a context)... :)

**Pull request merged**
