### PR TITLE
Architecture review

### PR DESCRIPTION
**Pull request by philarcher**
I have been through the doc and made a few suggested edits. Most notably, I am uncomfortable with the term "Digital Link Resolver".  I'm suggesting Identity Resolver (IDR) instead. The term "GS1 Digital Link" is obviously GS1-centric but removing the 'GS1' doesn't work (actually the term is a trademark of Panasonic!). ISO/IEC 18975 only says a little about resolvers. You need a specification like the specific "GS1-Conformant resolver" spec to turn it into an implementable standard. The ISO/IEC spec *does* mention RFC 9264 though and I think that's worth stating. I can say more on a near-future call.

### CODE REVIEW

**Comment by philarcher** [comment]
Incidentally, if the term "Identity Resolver" is accepted then the graphics will need updating. Also, almost as an aside, an 'IDR' would include a DID resolver too (not that I think DIDs are suitable as product IDs but that's a different discussion!)

**Comment by onthebreeze** [comment]
Thanks phil 

I've no strong attachment to the term DLR - and quite happy to call it something like identity resolver.  

The main thing is that we both recognise that it's not really enough to say "just implement iso 18975".

**Comment by onthebreeze** [comment]
I'll update the diagram right after the team agree to merge your PR

**Review by nissimsan — APPROVED** [review]
LGTM

**Pull request merged**
